version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - python3 -m pip install -U pip
      - python3 -m pip install -U poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
