services:
  api:
    container_name: pubg_tracker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - DJANGO_NINJA_SECRET_KEY=${DJANGO_NINJA_SECRET_KEY}
    ports:
      - 8000:8000
    expose:
      - 8000
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 2s
