# Generated by Django 5.0.6 on 2024-07-05 21:54

import backend.models.base
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', backend.models.base.AutoDateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('kill', models.IntegerField(default=-1)),
                ('assist', models.IntegerField(default=-1)),
                ('death', models.IntegerField(default=-1)),
                ('point', models.IntegerField(default=-1)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
