# Generated by Django 5.0.6 on 2024-07-05 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_record"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="game_id",
            new_name="game",
        ),
    ]
