# Generated by Django 5.0.6 on 2024-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_game_id_record_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='backend_gam_name_2bfe89_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['game', 'name'], name='backend_rec_game_id_bd68b0_idx'),
        ),
    ]
