# Generated by Django 5.0.6 on 2024-07-06 16:21

import backend.models.base
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_game_backend_gam_name_2bfe89_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', backend.models.base.AutoDateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('total_played', models.IntegerField(default=0)),
                ('total_assist', models.IntegerField(default=0)),
                ('total_death', models.IntegerField(default=0)),
                ('total_kill', models.IntegerField(default=0)),
                ('total_point', models.IntegerField(default=0)),
                ('valid_assist_match', models.IntegerField(default=0)),
                ('valid_death_match', models.IntegerField(default=0)),
                ('valid_kill_match', models.IntegerField(default=0)),
                ('valid_point_match', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='backend_gam_name_d2bf4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='backend_rec_game_id_853dc0_idx',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='backend_gam_name_2bfe89_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['created_at'], name='backend_gam_created_7d29c9_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['updated_at'], name='backend_gam_updated_bc2b74_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['name'], name='backend_rec_name_8479ce_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['name', 'game_id'], name='backend_rec_name_9e723f_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_at'], name='backend_rec_created_31c23a_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['updated_at'], name='backend_rec_updated_0dd2b4_idx'),
        ),
        migrations.AddField(
            model_name='stat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game'),
        ),
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['name'], name='backend_sta_name_157564_idx'),
        ),
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['name', 'game_id'], name='backend_sta_name_5824cf_idx'),
        ),
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['created_at'], name='backend_sta_created_d7f460_idx'),
        ),
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['updated_at'], name='backend_sta_updated_6a8fdc_idx'),
        ),
    ]
