# Generated by Django 5.0.6 on 2024-07-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_stat_remove_game_backend_gam_name_d2bf4e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='victory',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='total_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='total_won',
            field=models.IntegerField(default=0),
        ),
    ]
