name: Build and test with Tox

permissions: read-all

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

env:
  DJANGO_NINJA_SECRET_KEY: ${{ secrets.DJANGO_NINJA_SECRET_KEY }}

jobs:
  test_release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U tox
      - name: Tox
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          tox

      # - if: ${{ matrix.python-version == 3.12 }}
      #   name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@main
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: proafxin/tdm-tracker
      #     verbose: true
